name: Monitor citas Ayuntamiento

on:

  schedule:
    # Cada 5 minutos
    - cron: '*/5 * * * *'
    # Backup: cada hora (por si la anterior falla)
    - cron: '0 * * * *'

  # Permite lanzarlo manualmente
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group: monitor-job
  cancel-in-progress: false


jobs:

  monitor:

    runs-on: ubuntu-latest


    steps:

      - name: Descargar código
        uses: actions/checkout@v4


      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt


      - name: Ejecutar monitor
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          python monitor.py
        continue-on-error: true
        timeout-minutes: 5


      - name: Guardar estado
        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add estado.json


          if ! git diff --cached --quiet; then

            git commit -m "Actualizar estado"

            git push

          fi